//  Auth actions
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'

//  Dahboard
export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const GET_ALL_PROFILES = 'GET_ALL_PROFILES'

//  Errors
export const GET_ERRORS = 'GET_ERRORS'